name: Validate Data Schema (JSON)

on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install jsonlint
        run: npm install -g @prantlf/jsonlint
      - name: Validate DataSchema.json
        run: jsonlint $GITHUB_WORKSPACE/DataSchemaModified.json
